version: "3.9"

services:
  frontend:
    image: sham9394/frontend:latest
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - BACKEND_URL=http://backend:5000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend:
    image: sham9394/backend:latest
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:

networks:
  app-network:
    driver: overlay
